"""added two columns brand and model

Revision ID: 1afd263c1a1e
Revises: 4be34d7aafd7
Create Date: 2025-06-13 12:18:36.190718

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1afd263c1a1e'
down_revision = '4be34d7aafd7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('todo', schema=None) as batch_op:
        batch_op.add_column(sa.Column('brand', sa.String(length=500), nullable=True))
        batch_op.add_column(sa.Column('model', sa.String(length=500), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('todo', schema=None) as batch_op:
        batch_op.drop_column('model')
        batch_op.drop_column('brand')

    # ### end Alembic commands ###
