"""Add serial no column

Revision ID: 4755e81ec06e
Revises: 92ddf327e43d
Create Date: 2025-06-11 17:52:40.426746

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4755e81ec06e'
down_revision = '92ddf327e43d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('todo', schema=None) as batch_op:
        batch_op.add_column(sa.Column('serial', sa.String(length=500), nullable=True))
        batch_op.alter_column('floor',
               existing_type=sa.VARCHAR(length=500),
               nullable=True,
               existing_server_default=sa.text("'Unknown'"))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('todo', schema=None) as batch_op:
        batch_op.alter_column('floor',
               existing_type=sa.VARCHAR(length=500),
               nullable=False,
               existing_server_default=sa.text("'Unknown'"))
        batch_op.drop_column('serial')

    # ### end Alembic commands ###
