"""intial migration

Revision ID: 92ddf327e43d
Revises: 
Create Date: 2025-06-11 11:00:45.299430

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '92ddf327e43d'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('todo', schema=None) as batch_op:
        batch_op.add_column(sa.Column('floor', sa.String(length=500), nullable=False, server_default = "Unknown"))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('todo', schema=None) as batch_op:
        batch_op.drop_column('floor')

    # ### end Alembic commands ###
